name: Deploy to AWS Lambda

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LAMBDA_FUNCTION_NAME: ${{ github.ref == 'refs/heads/main' && 'taxi_data_hub_lambda_ingestion_raw_prd' || 'taxi_data_hub_lambda_ingestion_raw_dev' }}
      S3_PREFIX: ${{ github.ref == 'refs/heads/main' && 'prd/raw/' || 'dev/raw/' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/main' && secrets.AWS_ROLE_ARN_PRD || secrets.AWS_ROLE_ARN_DEV }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies and package Lambda
        run: |
          cd src/raw/aws_lambda
          python3 -m venv venv
          source venv/bin/activate
          mkdir -p build
          pip install -r aws_lambda_requirements.txt -t build
          cp *.py build
          cd build
          zip -r ../lambda_package.zip .
          cd ..

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --zip-file fileb://src/raw/aws_lambda/lambda_package.zip

      - name: Invoke Lambda Function
        run: |
          aws lambda invoke \
            --function-name $LAMBDA_FUNCTION_NAME \
            --invocation-type RequestResponse \
            --payload '{}' \
            response.json

          cat response.json