name: Deploy to AWS Lambda

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}
      LAMBDA_FUNCTION_NAME: ${{ github.ref == 'refs/heads/main' && 'taxi_data_hub_create_emr_curated_prd' || 'taxi_data_hub_create_emr_curated_dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/main' && secrets.AWS_ROLE_ARN_PRD || secrets.AWS_ROLE_ARN_DEV }} 
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          cd src
          zip -r curated.zip curated

          aws s3 cp curated/jobs/run_yellow_green_curate.py s3://taxi-data-hub/jobs/$ENV/run_yellow_green_curate.py
          aws s3 cp curated.zip s3://taxi-data-hub/jobs_dependencies/$ENV/curated.zip

      - name: Deploy to AWS Lambda
        run: |
          cd src
          zip lambda.zip curated/jobs/lambda_function.py

          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \ 
            --zip-file fileb://lambda.zip

      - name: Wait before setting environment variables
        run: sleep 15

      - name: Update Lambda Environment Variable
        run: |
          aws lambda update-function-configuration \
            --function-name $LAMBDA_FUNCTION_NAME \
            --environment "Variables={ENV=${ENV}}"