name: Deploy to AWS Lambda

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-region: us-east-1

      - name: Install dependencies and package Lambda
        run: |
          cd src/raw/aws_lambda
          python3 -m venv venv
          source venv/bin/activate
          mkdir -p build
          pip install -r aws_lambda_requirements.txt -t build
          cp *.py build
          cd build
          zip -r ../lambda_package.zip .
          cd ..

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name taxi_data_hub_lambda_ingestion_raw \
            --zip-file fileb://src/raw/aws_lambda/lambda_package.zip
